[general]
import = [
  #"~/.config/alacritty/themes/catppuccin-mocha.toml"
  #"~/.config/alacritty/themes/rose-pine.toml" 
]

[font]
size = 12.0

[font.bold]
#family = "JetBrains Mono Nerd Font"
family = "Iosevka Nerd Font Mono"
style = "Bold"

[font.bold_italic]
#family = "JetBrains Mono Nerd Font"
family = "Iosevka Nerd Font Mono"
style = "Bold Italic"

[font.italic]
#family = "JetBrains Mono Nerd Font"
family = "Iosevka Nerd Font Mono"
style = "Italic"

[font.normal]
#family = "JetBrains Mono Nerd Font"
family = "Iosevka Nerd Font Mono"
style = "Regular"
